### ISSUE TITLE
[Suggestion] Connected brackets

### ISSUE THREAD

**Issue by Matthysse** [mrh0/buildersaddition#12]
Hello!
I have a second suggestion! It would be cool if the brackets would connect to the vertical slabs from quark and your mod, to the walls, to the fences, and to the upper slabs (not like on the image, it would remove the lower part of the bracket). This would allow user to be more creative, to create city lanterns etc. The bracket would have the same lenght as now at the end (0,6 in the normal block after)

![2020-10-23_12 00 26](https://user-images.githubusercontent.com/32510957/96991079-39f27c00-1528-11eb-9800-f55cd34a4211.png)

**Comment by mrh0** [comment]
This is actually something I did consider when I made them but decided not to (I'm a bit lazy you see) but it wouldn't be too hard to do, I'll add it to the backburner.

**Comment by Matthysse** [comment]
Ok no problem!

**Comment by mrh0** [comment]
Support brackets now attach to Pillars, Walls and Fences as of 20201028b.
