### ISSUE TITLE
Water Dupe with the Cupboard

### ISSUE THREAD

**Issue by WenXin20** [mrh0/buildersaddition#16]
`Minecraft v1.16.4`

If a Cupboard is placed in water that is only one block deep, the top half will still become waterlogged. Breaking the cupboard also deletes the water source instead of leaving it behind. Some blocks are also missing waterlogging, which would be nice to see. 

Another couple of things I've noticed is that the  Iron Rod can be given the tag `#forge:rods/iron`, for compat with other mods that use it, such as the Ultimate Car mod or Silent Gear. Also, a lot of the blocks are too large when placed in an item frame.

**Comment by mrh0** [comment]
The Cupboard thing I'm aware of, I've tried to fix it but will probably just remove waterlogging on it. The Iron Rod is already tagged #forge:rods/iron. I'll take a look at the Item frame thing.

**Comment by WenXin20** [comment]
Thanks!
From taking a quick look, it looks like it could be happening because the `getStateForPlacement` is setting the state to be waterlogged instead of checking if the top half is in water or air, but I'm not entirely sure.
[Here's](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/649f84ef9fe063f8c72cc2d6344c6cf09c4b2023/src/main/java/pokecube/adventures/blocks/genetics/cloner/ClonerBlock.java#L129) a block that I previously added waterlogging for that also has two parts.

**Comment by mrh0** [comment]
Alright thanks, I'll take a look when I've got time!

**Comment by mrh0** [comment]
Fixed in 202012200a.
