### ISSUE TITLE
[1.16.4] Vertical Redstone Repeater/Comparator Dupe

### ISSUE THREAD

**Issue by NillerMedDild** [mrh0/buildersaddition#19]
Placing a Redstone Repeater or Redstone Comparator vertically doesn't use up the block, so you can very easily dupe them.

Video: https://user-images.githubusercontent.com/5300396/104733696-0ebfa780-577a-11eb-9a0a-fad70c2129ac.mp4

**Comment by mrh0** [comment]
oh; yeah, was supposed to fix that before I released it but totally forgot.

**Comment by useenzhekoay** [comment]
Extra question does it fix the conflict of use the item into the block such as spawner with Apothesis mod (right click redstone comparator to enhance spawner capability) and Ars Noveau's Glyph Press (right click use it as crafting recipe.)

**Comment by mrh0** [comment]
Both issues resolved in 20210118a.
Current work-around: https://github.com/NillerMedDild/Enigmatica6/issues/943#issuecomment-762181666
