### ISSUE TITLE
[1.16.4] Bookshelves can't contain all books

### ISSUE THREAD

**Issue by NillerMedDild** [mrh0/buildersaddition#21]
Several books cannot be inserted in Bookshelves, to name a few:
- occultism:dictionary_of_spirits
- alexsmobs:animal_dictionary

A config for specifying words that constitute accepted books (so I can add "dictionary" to the list) or a config for specific items that may go in what be nice.

Original report: https://github.com/NillerMedDild/Enigmatica6/issues/1069

**Comment by mrh0** [comment]
Fixed, will be in next release!

**Comment by NillerMedDild** [comment]
Thanks!

**Comment by NillerMedDild** [comment]
The guide from the mod Integrated Dynamics `On the Dynamics of Integration` cannot go in Bookshelves either :)
