### ISSUE TITLE
Texture Bug

### ISSUE THREAD

**Issue by DamienBrittan** [mrh0/buildersaddition#27]
Mod version - buildersaddition-1.16.4-20210214a
Forge : 1.16.5-forge-36.0.42
Optifine : OptiFine HD U G7

After placing shelves and bookshelves appears texture bug . It's probably happened after i updated my optifine from g7_pre10 to g7

Images - https://imgur.com/a/fcpYHFd

**Comment by mrh0** [comment]
yes, that looks like an Optifine bug.
