### ISSUE TITLE
Use tags in recipes

### ISSUE THREAD

**Issue by p3lim** [mrh0/buildersaddition#3]
An example is iron rods, there are other mods also providing this item (e.g. Immersive Engineering), so please use the tag instead of item everywhere.

**Comment by mrh0** [comment]
the iron rod is already tagged, I've tested it with Immersive Engineering.

**Comment by mrh0** [comment]
Confirmed that iron rods still work with IE.

**Comment by p3lim** [comment]
Other way around, use the tag in _your_ recipes, so IE iron rods can be used to craft your stuff.

**Comment by mrh0** [comment]
Oh yeah, you're right, totally forgot! Thanks, will fix.

**Comment by mrh0** [comment]
Fixed in 20200905a (I could still be missing something)
