### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by Sam-Chai** [mrh0/buildersaddition#30]
i have some suggestions for this mod:
- let slabs can mixed double slabs together like mod _Double Slabs_ ([https://www.curseforge.com/minecraft/mc-mods/double-slabs](https://www.curseforge.com/minecraft/mc-mods/double-slabs))
- can place torch on these slabs.(although on vertical slabs)
- more fence like mod _Custom Fence_ ([https://www.curseforge.com/minecraft/mc-mods/customfence](https://www.curseforge.com/minecraft/mc-mods/customfence)
- can add custom images or gifs in game.
- a computer can browse Internet
- some toilet's furniture like washbasin and shower. Also compatible create's or mekanism's fluid system.

**Comment by mrh0** [comment]
None of these things fit the vision I have for the mod.
