### ISSUE TITLE
Suggestion: Change panel's tag "type: <side>" to "facing: side" so that it doesn't mess up structure saving

### ISSUE THREAD

**Issue by MonolithBR** [mrh0/buildersaddition#34]
When you save a structure containing panels and paste it somewhere else rotated, the panels will be on the wrong orientation (maintaining the orientation they had instead of rotating along with the structure)
I believe using "facing" instead of "type" on the nbt would resolve this issue, but it might not.

I ran across it in survival using panels with Create Mod's Schematicannon

**Comment by mrh0** [comment]
the name isn't the issue but I'm working on a fix.

**Comment by mrh0** [comment]
Fixed in 20210730b, however only on 1.17.1 atm.

**Comment by mrh0** [comment]
in 1.16.5 20210807a
