### ISSUE TITLE
Trouble building project

### ISSUE THREAD

**Issue by mc-ganduron** [mrh0/buildersaddition#35]
I ran into errors when building the mod code. I'm hoping you can help me understand what I'm doing wrong.

1. Can't find QSPL classes referenced in [ExtArcade](https://github.com/mrh0/buildersaddition/blob/02a53ba74243c13f38da254608a6f0ee6b8a8741/src/main/java/com/mrh0/buildersaddition/qspl/ExtArcade.java) and [QSPLArcadeGame](https://github.com/mrh0/buildersaddition/blob/02a53ba74243c13f38da254608a6f0ee6b8a8741/src/main/java/com/mrh0/buildersaddition/qspl/QSPLArcadeGame.java). The compiler can't find any classes under package `com.mrh0.qspl`. I see they're in project QSPL, but I couldn't find a connection to the project in the gradle config or anywhere else.

2. [BaseStool](https://github.com/mrh0/buildersaddition/blob/02a53ba74243c13f38da254608a6f0ee6b8a8741/src/main/java/com/mrh0/buildersaddition/blocks/base/BaseStool.java#L32) vs [SeatEntity](https://github.com/mrh0/buildersaddition/blob/02a53ba74243c13f38da254608a6f0ee6b8a8741/src/main/java/com/mrh0/buildersaddition/entity/SeatEntity.java#L94-L110):

        buildersaddition\src\main\java\com\mrh0\buildersaddition\blocks\base\BaseStool.java:32: error: no suitable method found for createSeat(World,BlockPos,PlayerEntity)
                return SeatEntity.createSeat(worldIn, pos, player) ? ActionResultType.SUCCESS : ActionResultType.FAIL;
                                 ^
        method SeatEntity.createSeat(World,BlockPos,LivingEntity,double,SoundEvent) is not applicable
          (actual and formal argument lists differ in length)
        method SeatEntity.createSeat(World,BlockPos,LivingEntity,SoundEvent) is not applicable
          (actual and formal argument lists differ in length)

Thanks.

**Comment by mc-ganduron** [comment]
>  but I couldn't find a connection to the project in the gradle config...

I see a reference to [`libs/cspl_4.3.2.jar`](https://github.com/mrh0/buildersaddition/blob/02a53ba74243c13f38da254608a6f0ee6b8a8741/build.gradle#L109) in build.gradle, but I don't see the jar in the project. Is there an additional build step that's needed to create/copy that jar?

**Comment by mrh0** [comment]
Sorry, I never structured this for building, I'll fix it.

**Comment by mrh0** [comment]
It should be easier to build now, cspl isn't used in the mod anymore so I've removed the code that was left.

**Comment by mc-ganduron** [comment]
Thanks a lot. :)
