### ISSUE TITLE
1.17.1 - 37.0.27 - 20210730b

### ISSUE THREAD

**Issue by Snaitf** [mrh0/buildersaddition#38]
Made a white sofa chair, and after sitting in it, then trying to stand, it crashed my server.
Could no longer launch the server, getting the same error every time.
Had to remove the mod, launch the server, close it, and put the mod back to get it to launch.

Latest error log:
https://hastebin.com/duyaqilewu.yaml

**Comment by mrh0** [comment]
fixed in 20210810a
