### ISSUE TITLE
forge:books tag does not seem to allow books into the bookshelf

### ISSUE THREAD

**Issue by codewolf219** [mrh0/buildersaddition#41]
https://github.com/mrh0/buildersaddition/blob/ff64d85dde43171fb7f5181bd46ed4ec1d1df060/src/main/java/com/mrh0/buildersaddition/util/Util.java#L23

I've got Tinker's Construct 3 installed and the books (all have the forge:books tag) will not slot into the bookshelf (except for materials and you which there is an exception for).

I believe the problem is in the initialization of the tag (https://github.com/mrh0/buildersaddition/blob/ff64d85dde43171fb7f5181bd46ed4ec1d1df060/src/main/java/com/mrh0/buildersaddition/util/Util.java#L21)

I've had to change my tag initializations to be on demand, as when the static variable is initialized the tag has not been initialized yet.

BuildersAddition v20210517a
TConstruct 3.1.2.265
Forge 36.2.2

**Comment by mrh0** [comment]
Fixed in 20211016a.
