### ISSUE TITLE
Cupboard and hopper on the top - items disappearing

### ISSUE THREAD

**Issue by UnPik** [mrh0/buildersaddition#43]
Hi, 
when you attach a hopper on the upper part of a cupboard (on the top or on the side) items are collected from the hopper but the cupboard is empty. 
Using another mod named Jade we can see what seems to be a hidden inventory in the upper part of the cupboard.

Please see the attached video.

https://user-images.githubusercontent.com/11645302/137537807-a520f5eb-c86c-4366-b856-1ca1dd715942.mp4

PS: thanks for your job, I like your mod :)

**Comment by UnPik** [comment]
Sorry I forgot to include the mod version: buildersaddition-1.17.1-20210823a

**Comment by mrh0** [comment]
Fixed in 20211016a.
