### ISSUE TITLE
Enabling MIDI input causes a hard lockup when attempting to load on Linux, Java 11, Forge 36.2.8.

### ISSUE THREAD

**Issue by TheMuso** [mrh0/buildersaddition#44]
As per the subject. I do not get anything useful in the debug or latest logs. I am launching with MultiMC 0.6.13. I am using this mod as a part of SkyFactory One 1.0.1. I also tried with java 8 and there was no difference.

**Comment by mrh0** [comment]
I'm not going to try to fix this, way too edge-case for me to set up a Linux VM and test this.

**Comment by TheMuso** [comment]
That is ok I understand. Wanted to let you know anyway.
