### ISSUE TITLE
Placing a comparator on the side of a shulker box causes a crash

### ISSUE THREAD

**Issue by tjarvis91** [mrh0/buildersaddition#45]
[ComparatorPlaceOnShulkerCrash.txt](https://github.com/mrh0/buildersaddition/files/7430103/ComparatorPlaceOnShulkerCrash.txt)

Placing a comparator on the side of shulker boxes causes a crash. The crash isn't limited to the sides of shulker boxes, I was getting the same one placing them on the sides of a lot of blocks in a build with shulkers in it. I'm not sure what the exact conditions for the crash are.

**Comment by mrh0** [comment]
Update to latest version.
