### ISSUE TITLE
Pillar recipe does not work

### ISSUE THREAD

**Issue by demfels** [mrh0/buildersaddition#5]
Mincraft Version 1.15.2
Modpack: https://www.curseforge.com/minecraft/modpacks/ultimate-pack-1-15-2

We see the recipe in JEI, however, when we attempted to craft it in the proper workbench it does not allow us to create the item.

Server start log: 
[latest_5 (2).log](https://github.com/mrh0/buildersaddition/files/5183659/latest_5.2.log)

![image](https://user-images.githubusercontent.com/4838280/92399565-1dbd8b80-f0f0-11ea-8454-9815c5cabf04.png)

![image](https://user-images.githubusercontent.com/4838280/92399552-15fde700-f0f0-11ea-9955-a2a3007e4e13.png)

**Comment by mrh0** [comment]
This is strange, probably a problem with another mod, however, I no longer support 1.15.2 sorry.
