### ISSUE TITLE
Shop sign causing ticking world crash on placement

### ISSUE THREAD

**Issue by SigynLaufeyson** [mrh0/buildersaddition#50]
Minecraft 1.18.1
Forge 39.0.55
Builders Addition 20211208a

I tried to place the shop sign & the game crashed with this error:

The game crashed whilst exception ticking world
Error: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.mrh0.buildersaddition.tileentity.ShopSignTileEntity.save(net.minecraft.nbt.CompoundTag)'
Exit Code: -1

I suspect something in Forge changed since I had placed them just fine in a test world running Forge 39.0.45

**Comment by mrh0** [comment]
Fixed in 20220123a.
