### ISSUE TITLE
Shelf crashes game

### ISSUE THREAD

**Issue by atomiicos** [mrh0/buildersaddition#51]
the shelf item causes the game to crash. according to the crash log: ticking world

**Comment by mrh0** [comment]
Full log please

**Comment by atomiicos** [comment]
unfortunately i just closed my pc to go to sleep, but here’s the initial pop up. i’m sorry if it isn’t much help. I was playing with the latest version of forge for 1.18.1
![Uploading 92DF1622-A153-457F-9B7C-DDA7FC7269D4.jpeg…]()

**Comment by mrh0** [comment]
Fixed in 20220123a.
