### ISSUE TITLE
1.19 wont load correctly

### ISSUE THREAD

**Issue by Elektroi1** [mrh0/buildersaddition#59]
attached error report and latest log report

Failure message: Builders Crafts & Addition (buildersaddition) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

[crash-2022-07-16_19.17.29-fml.txt](https://github.com/mrh0/buildersaddition/files/9126816/crash-2022-07-16_19.17.29-fml.txt)

**Comment by SuperSuprano** [comment]
Also having this issue, lmk when it's fixed!

**Comment by UnPik** [comment]
Hi, I think that it could be related to what is mentioned in this post: https://forums.minecraftforge.net/topic/113464-119064-dont-use/

**Comment by ProsperCraft** [comment]
Same here-
.93 had another breaking change I think as well.

**Comment by mimi-min** [comment]
I'm also having this issue, I hope it gets fixed! 
I would really like to use this mod over some of the others that do similar things...

**Comment by mrh0** [comment]
fixed in 20220802a.

**Comment by UnPik** [comment]
Thanks a lot!
