### ISSUE TITLE
Help whit traslation

### ISSUE THREAD

**Issue by Yupoman** [mrh0/buildersaddition#8]
I made a translation by creating an es_ar.json file with its respective translation inside, but it is still in English

I don't have much experience in this, with other mods I did them the same way and it works

**Comment by mrh0** [comment]
You can see the other language jsons in my mod here: [https://github.com/mrh0/buildersaddition/tree/master/src/main/resources/assets/buildersaddition/lang]
Minecraft will reject a json if it is malformed, check the json for errors here: 
[https://jsonformatter.curiousconcept.com/]
or just google _json checker._

**Comment by Yupoman** [comment]
Oh how stupid, I was missing a "
Added to favorites, it is very useful, thank you very much!

[es_ar.zip](https://github.com/mrh0/buildersaddition/files/5243266/es_ar.zip)
[es_es.zip](https://github.com/mrh0/buildersaddition/files/5243267/es_es.zip)
(es_es may have some errors in exact words that I do not know)

**Comment by mrh0** [comment]
Thanks for the contribution!
