### ISSUE TITLE
Can't place paintings

### ISSUE THREAD

**Issue by Phasertokill** [mrh0/buildersaddition#84]
Adding Builders Crafts & Additions breaks all paintings where they can't be placed. Currently using a workaround by deleting the textures and tags for paintings from the mod which allows everything else in the mod to be used with the default paintings. I hope you're able to resolve this in an update soon!

**Comment by EugeneLeclerc** [comment]
Yup same here.

**Comment by Gbergz** [comment]
Can confirm. Any updates on this?

**Comment by mrh0** [comment]
I dont maintain this version of the mod anymore

**Comment by EugeneLeclerc** [comment]
> I dont maintain this version of the mod anymore

Which version are you maintaining? The Curseforge page still links here.

**Comment by mrh0** [comment]
2.X.X

**Comment by EugeneLeclerc** [comment]
> 2.X.X

Thats indeed the one I'm using: `buildersaddition2-neoforge-1.21-2.1.0.jar` to be exact. 

Where can I find the repository and/or issues for this version? Both the Curseforge and Modrinth pages of the mod still link to this one, and I'm not seeing another repository on your profile ^^

**Comment by mrh0** [comment]
Alright, my bad not sure why i thought you were using 1.X.X, ill look into it
